export const cartConstants = {
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',

    REMOVE_FROM_CART_SUCCESS: 'REMOVE_FROM_CART_SUCCESS',
    REMOVE_FROM_CART_FAILURE: 'REMOVE_FROM_CART_FAILURE',

    CLEAR_CART: 'CLEAR_CART'
};
