export const menuConstants = {
    ADD_SUCCESS: 'ADD_ITEM_SUCCESS',
    ADD_FAILURE: 'ADD_ITEM_FAILURE',

    EDIT_SUCCESS: 'EDIT_ITEM_SUCCESS',
    EDIT_FAILURE: 'EDIT_ITEM_FAILURE',

    PREVIEW_ITEM: 'PREVIEW_ITEM',
    RESET_ITEM: 'RESET_ITEM',

    SET_PUBLISH: 'PUBLISH_ITEM',
    SET_UNPUBLISH: 'UNPUBLISH_ITEM',
    SET_BLOCK: 'BLOCK_ITEM',
    SET_UNBLOCK: 'UNBLOCK_ITEM',

    PUBLISHED_STATUS: 'published',
    UNPUBLISHED_STATUS: 'unpublished',
    BLOCKED_STATUS: 'blocked',
};
