export const menuConstants = {
    ADD_SUCCESS: 'ADD_ITEM_SUCCESS',
    ADD_FAILURE: 'ADD_ITEM_FAILURE',

    EDIT_SUCCESS: 'EDIT_ITEM_SUCCESS',
    EDIT_FAILURE: 'EDIT_ITEM_FAILURE',

    GET_ITEM_SUCCESS: 'GET_ITEM_SUCCESS',
    GET_ITEM_FAILURE: 'GET_ITEM_FAILURE',

    GETALL_SUCCESS: 'GETALL_SUCCESS',
    GETALL_FAILURE: 'GETALL_FAILURE',

    PUBLISH_SUCCESS: 'PUBLISH_SUCCESS',
    PUBLISH_FAILURE: 'PUBLISH_FAILURE',
    UNPUBLISH_SUCCESS: 'UNPUBLISH_SUCCESS',
    UNPUBLISH_FAILURE: 'UNPUBLISH_FAILURE',

    BLOCK_SUCCESS: 'BLOCK_SUCCESS',
    BLOCK_FAILURE: 'BLOCK_FAILURE',
    UNBLOCK_SUCCESS: 'UNBLOCK_SUCCESS',
    UNBLOCK_FAILURE: 'UNBLOCK_FAILURE',

    PUBLISHED_STATUS: 'published',
    UNPUBLISHED_STATUS: 'unpublished',
    BLOCKED_STATUS: 'blocked',
};
