export const orderConstants = {
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',

    ASSIGN_ORDER_SUCCESS: 'ORDER_ASSIGNED_SUCCESS',
    ASSIGN_ORDER_FAILURE: 'ORDER_ASSIGNED_FAILURE',

    DELIVER_ORDER_SUCCESS: 'DELIVER_ORDER_SUCCESS',
    DELIVER_ORDER_FAILURE: 'DELIVER_ORDER_FAILURE',

    PENDING_STATUS: 'PENDING',
    IN_PROGRESS_STATUS: 'IN_PROGRESS',
    DELIVERED_STATUS: 'DELIVERED',
};
