export const orderConstants = {
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',

    PENDING_STATUS: 'PENDING',
    IN_PROGRESS_STATUS: 'IN_PROGRESS',
    DELIVERED_STATUS: 'DELIVERED',
};
